/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgcCard: typeof import('./src/components/AgcCard/AgcCard.vue')['default']
    AgcCollapse: typeof import('./src/components/AgcCollapse/AgcCollapse.vue')['default']
    AgcCollapseItem: typeof import('./src/components/AgcCollapseItem/AgcCollapseItem.vue')['default']
    AgcHeader: typeof import('./src/components/AgcHeader/AgcHeader.vue')['default']
    AgcSpeedDials: typeof import('./src/components/AgcSpeedDials/AgcSpeedDials.vue')['default']
    AgcTabPane: typeof import('./src/components/AgcTabPane/AgcTabPane.vue')['default']
    AgcTabs: typeof import('./src/components/AgcTabs/AgcTabs.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
