/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgcButton: typeof import('./src/components/atoms/AgcButton/AgcButton.vue')['default']
    AgcCard: typeof import('./src/components/atoms/AgcCard/AgcCard.vue')['default']
    AgcCollapse: typeof import('./src/components/atoms/AgcCollapse/AgcCollapse.vue')['default']
    AgcCollapseItem: typeof import('./src/components/atoms/AgcCollapseItem/AgcCollapseItem.vue')['default']
    AgcDialog: typeof import('./src/components/atoms/AgcDialog/AgcDialog.vue')['default']
    AgcForm: typeof import('./src/components/atoms/AgcForm/AgcForm.vue')['default']
    AgcFormItem: typeof import('./src/components/atoms/AgcFormItem/AgcFormItem.vue')['default']
    AgcHeader: typeof import('./src/components/molecles/AgcHeader/AgcHeader.vue')['default']
    AgcIcon: typeof import('./src/components/atoms/AgcIcon/AgcIcon.vue')['default']
    AgcInput: typeof import('./src/components/atoms/AgcInput/AgcInput.vue')['default']
    AgcPopover: typeof import('./src/components/atoms/AgcPopover/AgcPopover.vue')['default']
    AgcPopoverInlineEditor: typeof import('./src/components/molecles/AgcPopoverInlineEditor/AgcPopoverInlineEditor.vue')['default']
    AgcProjectCard: typeof import('./src/components/molecles/AgcProjectCard/AgcProjectCard.vue')['default']
    AgcSpeedDials: typeof import('./src/components/AgcSpeedDials/AgcSpeedDials.vue')['default']
    AgcTabPane: typeof import('./src/components/atoms/AgcTabPane/AgcTabPane.vue')['default']
    AgcTabs: typeof import('./src/components/atoms/AgcTabs/AgcTabs.vue')['default']
    AgcTag: typeof import('./src/components/atoms/AgcTag/AgcTag.vue')['default']
    AgcTaskCard: typeof import('./src/components/molecles/AgcTaskCard/AgcTaskCard.vue')['default']
    AgcTextInlineEditor: typeof import('./src/components/molecles/AgcTextInlineEditor/AgcTextInlineEditor.vue')['default']
    AgcToolbar: typeof import('./src/components/molecles/AgcToolbar/AgcToolbar.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
